all:
	pdflatex  wall.tex
	pdflatex  -jobname=0 "\def\numpic{0} \input{main.tex}"
	pdflatex  -jobname=1 "\def\numpic{1} \input{main.tex}"
	pdflatex  -jobname=2 "\def\numpic{2} \input{main.tex}"
	pdflatex  -jobname=3 "\def\numpic{3} \input{main.tex}"
	pdflatex  -jobname=4 "\def\numpic{4} \input{main.tex}"
	pdflatex  -jobname=5 "\def\numpic{5} \input{main.tex}"
	pdflatex  -jobname=6 "\def\numpic{6} \input{main.tex}"
	pdflatex  -jobname=7 "\def\numpic{7} \input{main.tex}"
	pdflatex  -jobname=8 "\def\numpic{8} \input{main.tex}"
	pdflatex  -jobname=9 "\def\numpic{9} \input{main.tex}"
	pdflatex  -jobname=10 "\def\numpic{10} \input{main.tex}"
	pdflatex  -jobname=11 "\def\numpic{11} \input{main.tex}"
	pdflatex  -jobname=12 "\def\numpic{12} \input{main.tex}"
	pdflatex  -jobname=13 "\def\numpic{13} \input{main.tex}"
	pdflatex  -jobname=14 "\def\numpic{14} \input{main.tex}"
	pdflatex  -jobname=15 "\def\numpic{15} \input{main.tex}"
	pdflatex  -jobname=16 "\def\numpic{16} \input{main.tex}"
	pdflatex  -jobname=17 "\def\numpic{17} \input{main.tex}"
	pdflatex  -jobname=18 "\def\numpic{18} \input{main.tex}"
	pdflatex  -jobname=19 "\def\numpic{19} \input{main.tex}"
	pdflatex  -jobname=20 "\def\numpic{20} \input{main.tex}"
	pdflatex  -jobname=21 "\def\numpic{21} \input{main.tex}"
clean:
        find . -name '*.aux' -type f -exec rm -rf {} \;
        find . -name '*.bbl' -type f -exec rm -rf {} \;
        find . -name '*.blg' -type f -exec rm -rf {} \;
        find . -name '*.log' -type f -exec rm -rf {} \;
        find . -name '*.nav' -type f -exec rm -rf {} \;
        find . -name '*.out' -type f -exec rm -rf {} \;
        find . -name '*.snm' -type f -exec rm -rf {} \;
        find . -name '*.toc' -type f -exec rm -rf {} \;
        find . -name '*.vrb' -type f -exec rm -rf {} \;

